export interface NigeriaState {
  label: string;
  value: string;
}

export interface NigeriaCity {
  label: string;
  value: string;
}

export interface NigeriaLocations {
  [stateValue: string]: NigeriaCity[];
}

export const nigeriaStates: NigeriaState[] = [
  { label: 'Abia', value: 'abia' },
  { label: 'Adamawa', value: 'adamawa' },
  { label: 'Akwa Ibom', value: 'akwa_ibom' },
  { label: 'Anambra', value: 'anambra' },
  { label: 'Bauchi', value: 'bauchi' },
  { label: 'Bayelsa', value: 'bayelsa' },
  { label: 'Benue', value: 'benue' },
  { label: 'Borno', value: 'borno' },
  { label: 'Cross River', value: 'cross_river' },
  { label: 'Delta', value: 'delta' },
  { label: 'Ebonyi', value: 'ebonyi' },
  { label: 'Edo', value: 'edo' },
  { label: 'Ekiti', value: 'ekiti' },
  { label: 'Enugu', value: 'enugu' },
  { label: 'FCT (Abuja)', value: 'fct' },
  { label: 'Gombe', value: 'gombe' },
  { label: 'Imo', value: 'imo' },
  { label: 'Jigawa', value: 'jigawa' },
  { label: 'Kaduna', value: 'kaduna' },
  { label: 'Kano', value: 'kano' },
  { label: 'Katsina', value: 'katsina' },
  { label: 'Kebbi', value: 'kebbi' },
  { label: 'Kogi', value: 'kogi' },
  { label: 'Kwara', value: 'kwara' },
  { label: 'Lagos', value: 'lagos' },
  { label: 'Nasarawa', value: 'nasarawa' },
  { label: 'Niger', value: 'niger' },
  { label: 'Ogun', value: 'ogun' },
  { label: 'Ondo', value: 'ondo' },
  { label: 'Osun', value: 'osun' },
  { label: 'Oyo', value: 'oyo' },
  { label: 'Plateau', value: 'plateau' },
  { label: 'Rivers', value: 'rivers' },
  { label: 'Sokoto', value: 'sokoto' },
  { label: 'Taraba', value: 'taraba' },
  { label: 'Yobe', value: 'yobe' },
  { label: 'Zamfara', value: 'zamfara' },
];

export const nigeriaCitiesByState: NigeriaLocations = {
  abia: [
    { label: 'Aba', value: 'aba' },
    { label: 'Umuahia', value: 'umuahia' },
    { label: 'Ohafia', value: 'ohafia' },
    { label: 'Arochukwu', value: 'arochukwu' },
    { label: 'Bende', value: 'bende' },
    { label: 'Isuikwuato', value: 'isuikwuato' },
    { label: 'Osisioma', value: 'osisioma' },
    { label: 'Ugwunagbo', value: 'ugwunagbo' },
    { label: 'Ukwa East', value: 'ukwa_east' },
    { label: 'Ukwa West', value: 'ukwa_west' },
  ],
  adamawa: [
    { label: 'Yola', value: 'yola' },
    { label: 'Mubi', value: 'mubi' },
    { label: 'Numan', value: 'numan' },
    { label: 'Jimeta', value: 'jimeta' },
    { label: 'Ganye', value: 'ganye' },
    { label: 'Gombi', value: 'gombi' },
    { label: 'Jalingo', value: 'jalingo' },
    { label: 'Madagali', value: 'madagali' },
    { label: 'Michika', value: 'michika' },
    { label: 'Song', value: 'song' },
  ],
  akwa_ibom: [
    { label: 'Uyo', value: 'uyo' },
    { label: 'Eket', value: 'eket' },
    { label: 'Ikot Ekpene', value: 'ikot_ekpene' },
    { label: 'Oron', value: 'oron' },
    { label: 'Abak', value: 'abak' },
    { label: 'Etinan', value: 'etinan' },
    { label: 'Ikot Abasi', value: 'ikot_abasi' },
    { label: 'Itu', value: 'itu' },
    { label: 'Mkpat Enin', value: 'mkpat_enin' },
    { label: 'Nsit Ubium', value: 'nsit_ubium' },
  ],
  anambra: [
    { label: 'Awka', value: 'awka' },
    { label: 'Onitsha', value: 'onitsha' },
    { label: 'Nnewi', value: 'nnewi' },
    { label: 'Ekwulobia', value: 'ekwulobia' },
    { label: 'Aguata', value: 'aguata' },
    { label: 'Ihiala', value: 'ihiala' },
    { label: 'Ogidi', value: 'ogidi' },
    { label: 'Ozubulu', value: 'ozubulu' },
    { label: 'Ukpo', value: 'ukpo' },
    { label: 'Umunze', value: 'umunze' },
  ],
  bauchi: [
    { label: 'Bauchi', value: 'bauchi_city' },
    { label: 'Azare', value: 'azare' },
    { label: 'Misau', value: 'misau' },
    { label: 'Katagum', value: 'katagum' },
    { label: 'Alkaleri', value: 'alkaleri' },
    { label: 'Darazo', value: 'darazo' },
    { label: 'Ganjuwa', value: 'ganjuwa' },
    { label: 'Ningi', value: 'ningi' },
    { label: 'Tafawa Balewa', value: 'tafawa_balewa' },
    { label: 'Warji', value: 'warji' },
  ],
  bayelsa: [
    { label: 'Yenagoa', value: 'yenagoa' },
    { label: 'Ogbia', value: 'ogbia' },
    { label: 'Brass', value: 'brass' },
    { label: 'Ekeremor', value: 'ekeremor' },
    { label: 'Kolokuma/Opokuma', value: 'kolokuma_opokuma' },
    { label: 'Nembe', value: 'nembe' },
    { label: 'Sagbama', value: 'sagbama' },
    { label: 'Southern Ijaw', value: 'southern_ijaw' },
  ],
  benue: [
    { label: 'Makurdi', value: 'makurdi' },
    { label: 'Gboko', value: 'gboko' },
    { label: 'Otukpo', value: 'otukpo' },
    { label: 'Katsina-Ala', value: 'katsina_ala' },
    { label: 'Adikpo', value: 'adikpo' },
    { label: 'Aliade', value: 'aliade' },
    { label: 'Oju', value: 'oju' },
    { label: 'Oturkpo', value: 'oturkpo' },
    { label: 'Ugbokolo', value: 'ugbokolo' },
    { label: 'Zaki Biam', value: 'zaki_biam' },
  ],
  borno: [
    { label: 'Maiduguri', value: 'maiduguri' },
    { label: 'Biu', value: 'biu' },
    { label: 'Dikwa', value: 'dikwa' },
    { label: 'Gwoza', value: 'gwoza' },
    { label: 'Konduga', value: 'konduga' },
    { label: 'Kukawa', value: 'kukawa' },
    { label: 'Kwaya Kusar', value: 'kwaya_kusar' },
    { label: 'Monguno', value: 'monguno' },
    { label: 'Ngala', value: 'ngala' },
    { label: 'Shani', value: 'shani' },
  ],
  cross_river: [
    { label: 'Calabar', value: 'calabar' },
    { label: 'Ikom', value: 'ikom' },
    { label: 'Ogoja', value: 'ogoja' },
    { label: 'Ugep', value: 'ugep' },
    { label: 'Akamkpa', value: 'akamkpa' },
    { label: 'Bekwarra', value: 'bekwarra' },
    { label: 'Biase', value: 'biase' },
    { label: 'Obanliku', value: 'obanliku' },
    { label: 'Obubra', value: 'obubra' },
    { label: 'Yakurr', value: 'yakurr' },
  ],
  delta: [
    { label: 'Asaba', value: 'asaba' },
    { label: 'Warri', value: 'warri' },
    { label: 'Sapele', value: 'sapele' },
    { label: 'Ughelli', value: 'ughelli' },
    { label: 'Abraka', value: 'abraka' },
    { label: 'Agbor', value: 'agbor' },
    { label: 'Bomadi', value: 'bomadi' },
    { label: 'Burutu', value: 'burutu' },
    { label: 'Kwale', value: 'kwale' },
    { label: 'Ozoro', value: 'ozoro' },
    { label: 'Patani', value: 'patani' },
  ],
  ebonyi: [
    { label: 'Abakaliki', value: 'abakaliki' },
    { label: 'Afikpo', value: 'afikpo' },
    { label: 'Onueke', value: 'onueke' },
    { label: 'Ezza', value: 'ezza' },
    { label: 'Ikwo', value: 'ikwo' },
    { label: 'Ishielu', value: 'ishielu' },
    { label: 'Ohaozara', value: 'ohaozara' },
    { label: 'Ohaukwu', value: 'ohaukwu' },
    { label: 'Onicha', value: 'onicha' },
  ],
  edo: [
    { label: 'Benin City', value: 'benin_city' },
    { label: 'Auchi', value: 'auchi' },
    { label: 'Ekpoma', value: 'ekpoma' },
    { label: 'Uromi', value: 'uromi' },
    { label: 'Akoko-Edo', value: 'akoko_edo' },
    { label: 'Etsako East', value: 'etsako_east' },
    { label: 'Igueben', value: 'igueben' },
    { label: 'Orhionmwon', value: 'orhionmwon' },
    { label: 'Ovia North-East', value: 'ovia_north_east' },
    { label: 'Uhunmwonde', value: 'uhunmwonde' },
  ],
  ekiti: [
    { label: 'Ado-Ekiti', value: 'ado_ekiti' },
    { label: 'Ikere-Ekiti', value: 'ikere_ekiti' },
    { label: 'Oye-Ekiti', value: 'oye_ekiti' },
    { label: 'Efon-Alaaye', value: 'efon_alaaye' },
    { label: 'Emure-Ekiti', value: 'emure_ekiti' },
    { label: 'Ijero-Ekiti', value: 'ijero_ekiti' },
    { label: 'Ikole-Ekiti', value: 'ikole_ekiti' },
    { label: 'Ilawe-Ekiti', value: 'ilawe_ekiti' },
    { label: 'Ise-Ekiti', value: 'ise_ekiti' },
    { label: 'Omuo-Ekiti', value: 'omuo_ekiti' },
  ],
  enugu: [
    { label: 'Enugu', value: 'enugu_city' },
    { label: 'Nsukka', value: 'nsukka' },
    { label: 'Agbani', value: 'agbani' },
    { label: 'Awgu', value: 'awgu' },
    { label: 'Oji River', value: 'oji_river' },
    { label: 'Udi', value: 'udi' },
    { label: 'Igbo-Eze North', value: 'igbo_eze_north' },
    { label: 'Igbo-Eze South', value: 'igbo_eze_south' },
    { label: 'Nkanu East', value: 'nkanu_east' },
    { label: 'Nnewi', value: 'nnewi_enugu' },
  ],
  fct: [
    { label: 'Abuja', value: 'abuja' },
    { label: 'Gwagwalada', value: 'gwagwalada' },
    { label: 'Kuje', value: 'kuje' },
    { label: 'Bwari', value: 'bwari' },
    { label: 'Abaji', value: 'abaji' },
    { label: 'Kwali', value: 'kwali' },
    { label: 'Lugbe', value: 'lugbe' },
    { label: 'Nyanya', value: 'nyanya' },
    { label: 'Kubwa', value: 'kubwa' },
    { label: 'Zuba', value: 'zuba' },
  ],
  gombe: [
    { label: 'Gombe', value: 'gombe_city' },
    { label: 'Kumo', value: 'kumo' },
    { label: 'Billiri', value: 'billiri' },
    { label: 'Deba', value: 'deba' },
    { label: 'Kaltungo', value: 'kaltungo' },
    { label: 'Nafada', value: 'nafada' },
    { label: 'Bajoga', value: 'bajoga' },
    { label: 'Funakaye', value: 'funakaye' },
    { label: 'Yamaltu', value: 'yamaltu' },
  ],
  imo: [
    { label: 'Owerri', value: 'owerri' },
    { label: 'Orlu', value: 'orlu' },
    { label: 'Okigwe', value: 'okigwe' },
    { label: 'Oguta', value: 'oguta' },
    { label: 'Aboh Mbaise', value: 'aboh_mbaise' },
    { label: 'Ehime Mbano', value: 'ehime_mbano' },
    { label: 'Ezinihitte', value: 'ezinihitte' },
    { label: 'Ihitte/Uboma', value: 'ihitte_uboma' },
    { label: 'Ikeduru', value: 'ikeduru' },
    { label: 'Mbaitoli', value: 'mbaitoli' },
    { label: 'Ngor Okpala', value: 'ngor_okpala' },
  ],
  jigawa: [
    { label: 'Dutse', value: 'dutse' },
    { label: 'Hadejia', value: 'hadejia' },
    { label: 'Gumel', value: 'gumel' },
    { label: 'Kazaure', value: 'kazaure' },
    { label: 'Birnin Kudu', value: 'birnin_kudu' },
    { label: 'Babura', value: 'babura' },
    { label: 'Garki', value: 'garki' },
    { label: 'Gwaram', value: 'gwaram' },
    { label: 'Kaugama', value: 'kaugama' },
    { label: 'Maigatari', value: 'maigatari' },
  ],
  kaduna: [
    { label: 'Kaduna', value: 'kaduna_city' },
    { label: 'Zaria', value: 'zaria' },
    { label: 'Kafanchan', value: 'kafanchan' },
    { label: 'Kagoro', value: 'kagoro' },
    { label: 'Birnin Gwari', value: 'birnin_gwari' },
    { label: 'Giwa', value: 'giwa' },
    { label: 'Ikara', value: 'ikara' },
    { label: 'Kachia', value: 'kachia' },
    { label: 'Kajuru', value: 'kajuru' },
    { label: 'Makarfi', value: 'makarfi' },
    { label: 'Soba', value: 'soba' },
  ],
  kano: [
    { label: 'Kano', value: 'kano_city' },
    { label: 'Wudil', value: 'wudil' },
    { label: 'Rano', value: 'rano' },
    { label: 'Gaya', value: 'gaya' },
    { label: 'Bichi', value: 'bichi' },
    { label: 'Dambatta', value: 'dambatta' },
    { label: 'Doguwa', value: 'doguwa' },
    { label: 'Fagge', value: 'fagge' },
    { label: 'Gabasawa', value: 'gabasawa' },
    { label: 'Gwale', value: 'gwale' },
    { label: 'Nasarawa', value: 'nasarawa_kano' },
    { label: 'Tarauni', value: 'tarauni' },
    { label: 'Ungogo', value: 'ungogo' },
  ],
  katsina: [
    { label: 'Katsina', value: 'katsina_city' },
    { label: 'Daura', value: 'daura' },
    { label: 'Funtua', value: 'funtua' },
    { label: 'Malumfashi', value: 'malumfashi' },
    { label: 'Dutsin-Ma', value: 'dutsin_ma' },
    { label: 'Batagarawa', value: 'batagarawa' },
    { label: 'Baure', value: 'baure' },
    { label: 'Bindawa', value: 'bindawa' },
    { label: 'Charanchi', value: 'charanchi' },
    { label: 'Ingawa', value: 'ingawa' },
    { label: 'Mani', value: 'mani' },
  ],
  kebbi: [
    { label: 'Birnin Kebbi', value: 'birnin_kebbi' },
    { label: 'Argungu', value: 'argungu' },
    { label: 'Yauri', value: 'yauri' },
    { label: 'Zuru', value: 'zuru' },
    { label: 'Bagudo', value: 'bagudo' },
    { label: 'Bunza', value: 'bunza' },
    { label: 'Fakai', value: 'fakai' },
    { label: 'Gwandu', value: 'gwandu' },
    { label: 'Jega', value: 'jega' },
    { label: 'Koko/Besse', value: 'koko_besse' },
  ],
  kogi: [
    { label: 'Lokoja', value: 'lokoja' },
    { label: 'Okene', value: 'okene' },
    { label: 'Kabba', value: 'kabba' },
    { label: 'Ankpa', value: 'ankpa' },
    { label: 'Idah', value: 'idah' },
    { label: 'Ajaokuta', value: 'ajaokuta' },
    { label: 'Dekina', value: 'dekina' },
    { label: 'Ibaji', value: 'ibaji' },
    { label: 'Ijumu', value: 'ijumu' },
    { label: 'Mopa-Muro', value: 'mopa_muro' },
    { label: 'Okehi', value: 'okehi' },
  ],
  kwara: [
    { label: 'Ilorin', value: 'ilorin' },
    { label: 'Offa', value: 'offa' },
    { label: 'Erin-Ile', value: 'erin_ile' },
    { label: 'Jebba', value: 'jebba' },
    { label: 'Lafiagi', value: 'lafiagi' },
    { label: 'Bode Saadu', value: 'bode_saadu' },
    { label: 'Idofian', value: 'idofian' },
    { label: 'Kaiama', value: 'kaiama' },
    { label: 'Omu-Aran', value: 'omu_aran' },
    { label: 'Patigi', value: 'patigi' },
  ],
  lagos: [
    { label: 'Ikeja', value: 'ikeja' },
    { label: 'Lagos Island', value: 'lagos_island' },
    { label: 'Victoria Island', value: 'victoria_island' },
    { label: 'Lekki', value: 'lekki' },
    { label: 'Ikorodu', value: 'ikorodu' },
    { label: 'Surulere', value: 'surulere' },
    { label: 'Yaba', value: 'yaba' },
    { label: 'Mushin', value: 'mushin' },
    { label: 'Oshodi', value: 'oshodi' },
    { label: 'Alimosho', value: 'alimosho' },
    { label: 'Apapa', value: 'apapa' },
    { label: 'Badagry', value: 'badagry' },
    { label: 'Epe', value: 'epe' },
    { label: 'Agege', value: 'agege' },
    { label: 'Shomolu', value: 'shomolu' },
    { label: 'Eti-Osa', value: 'eti_osa' },
    { label: 'Kosofe', value: 'kosofe' },
    { label: 'Lagos Mainland', value: 'lagos_mainland' },
    { label: 'Ojo', value: 'ojo' },
    { label: 'Ifako-Ijaiye', value: 'ifako_ijaiye' },
  ],
  nasarawa: [
    { label: 'Lafia', value: 'lafia' },
    { label: 'Keffi', value: 'keffi' },
    { label: 'Akwanga', value: 'akwanga' },
    { label: 'Nasarawa', value: 'nasarawa_city' },
    { label: 'Awe', value: 'awe' },
    { label: 'Doma', value: 'doma' },
    { label: 'Karu', value: 'karu' },
    { label: 'Keana', value: 'keana' },
    { label: 'Kokona', value: 'kokona' },
    { label: 'Toto', value: 'toto' },
  ],
  niger: [
    { label: 'Minna', value: 'minna' },
    { label: 'Suleja', value: 'suleja' },
    { label: 'Bida', value: 'bida' },
    { label: 'Kontagora', value: 'kontagora' },
    { label: 'Agaie', value: 'agaie' },
    { label: 'Agwara', value: 'agwara' },
    { label: 'Borgu', value: 'borgu' },
    { label: 'Gbako', value: 'gbako' },
    { label: 'Gurara', value: 'gurara' },
    { label: 'Lapai', value: 'lapai' },
    { label: 'Paikoro', value: 'paikoro' },
    { label: 'Rafi', value: 'rafi' },
  ],
  ogun: [
    { label: 'Abeokuta', value: 'abeokuta' },
    { label: 'Sagamu', value: 'sagamu' },
    { label: 'Ijebu-Ode', value: 'ijebu_ode' },
    { label: 'Ilaro', value: 'ilaro' },
    { label: 'Ota', value: 'ota' },
    { label: 'Ifo', value: 'ifo' },
    { label: 'Ago-Iwoye', value: 'ago_iwoye' },
    { label: 'Ewekoro', value: 'ewekoro' },
    { label: 'Ijebu-Igbo', value: 'ijebu_igbo' },
    { label: 'Owode', value: 'owode' },
  ],
  ondo: [
    { label: 'Akure', value: 'akure' },
    { label: 'Ondo', value: 'ondo_city' },
    { label: 'Okitipupa', value: 'okitipupa' },
    { label: 'Owo', value: 'owo' },
    { label: 'Ore', value: 'ore' },
    { label: 'Idanre', value: 'idanre' },
    { label: 'Ifedore', value: 'ifedore' },
    { label: 'Ilaje', value: 'ilaje' },
    { label: 'Ile Oluji', value: 'ile_oluji' },
    { label: 'Irele', value: 'irele' },
    { label: 'Odigbo', value: 'odigbo' },
  ],
  osun: [
    { label: 'Osogbo', value: 'osogbo' },
    { label: 'Ile-Ife', value: 'ile_ife' },
    { label: 'Ilesa', value: 'ilesa' },
    { label: 'Ede', value: 'ede' },
    { label: 'Iwo', value: 'iwo' },
    { label: 'Ikirun', value: 'ikirun' },
    { label: 'Inisa', value: 'inisa' },
    { label: 'Ipetumodu', value: 'ipetumodu' },
    { label: 'Iragbiji', value: 'iragbiji' },
    { label: 'Modakeke', value: 'modakeke' },
    { label: 'Oke-Ila', value: 'oke_ila' },
  ],
  oyo: [
    { label: 'Ibadan', value: 'ibadan' },
    { label: 'Ogbomosho', value: 'ogbomosho' },
    { label: 'Oyo', value: 'oyo_city' },
    { label: 'Iseyin', value: 'iseyin' },
    { label: 'Saki', value: 'saki' },
    { label: 'Eruwa', value: 'eruwa' },
    { label: 'Fiditi', value: 'fiditi' },
    { label: 'Igboho', value: 'igboho' },
    { label: 'Igbo-Ora', value: 'igbo_ora' },
    { label: 'Igangan', value: 'igangan' },
    { label: 'Lalupon', value: 'lalupon' },
    { label: 'Okeho', value: 'okeho' },
  ],
  plateau: [
    { label: 'Jos', value: 'jos' },
    { label: 'Bukuru', value: 'bukuru' },
    { label: 'Shendam', value: 'shendam' },
    { label: 'Pankshin', value: 'pankshin' },
    { label: 'Barkin Ladi', value: 'barkin_ladi' },
    { label: 'Bassa', value: 'bassa' },
    { label: 'Bokkos', value: 'bokkos' },
    { label: 'Jos East', value: 'jos_east' },
    { label: 'Kanke', value: 'kanke' },
    { label: 'Langtang', value: 'langtang' },
    { label: 'Mangu', value: 'mangu' },
    { label: 'Mikang', value: 'mikang' },
  ],
  rivers: [
    { label: 'Port Harcourt', value: 'port_harcourt' },
    { label: 'Bonny', value: 'bonny' },
    { label: 'Degema', value: 'degema' },
    { label: 'Eleme', value: 'eleme' },
    { label: 'Obio-Akpor', value: 'obio_akpor' },
    { label: 'Okrika', value: 'okrika' },
    { label: 'Omuma', value: 'omuma' },
    { label: 'Opobo/Nkoro', value: 'opobo_nkoro' },
    { label: 'Oyigbo', value: 'oyigbo' },
    { label: 'Tai', value: 'tai' },
    { label: 'Asari-Toru', value: 'asari_toru' },
  ],
  sokoto: [
    { label: 'Sokoto', value: 'sokoto_city' },
    { label: 'Tambuwal', value: 'tambuwal' },
    { label: 'Bodinga', value: 'bodinga' },
    { label: 'Dange Shuni', value: 'dange_shuni' },
    { label: 'Gada', value: 'gada' },
    { label: 'Goronyo', value: 'goronyo' },
    { label: 'Gudu', value: 'gudu' },
    { label: 'Gwadabawa', value: 'gwadabawa' },
    { label: 'Ilela', value: 'ilela' },
    { label: 'Isa', value: 'isa' },
    { label: 'Kware', value: 'kware' },
  ],
  taraba: [
    { label: 'Jalingo', value: 'jalingo_city' },
    { label: 'Wukari', value: 'wukari' },
    { label: 'Bali', value: 'bali' },
    { label: 'Gashaka', value: 'gashaka' },
    { label: 'Gassol', value: 'gassol' },
    { label: 'Ibi', value: 'ibi' },
    { label: 'Karim Lamido', value: 'karim_lamido' },
    { label: 'Kurmi', value: 'kurmi' },
    { label: 'Lau', value: 'lau' },
    { label: 'Sardauna', value: 'sardauna' },
    { label: 'Takum', value: 'takum' },
    { label: 'Ussa', value: 'ussa' },
    { label: 'Zing', value: 'zing' },
  ],
  yobe: [
    { label: 'Damaturu', value: 'damaturu' },
    { label: 'Potiskum', value: 'potiskum' },
    { label: 'Gashua', value: 'gashua' },
    { label: 'Nguru', value: 'nguru' },
    { label: 'Bade', value: 'bade' },
    { label: 'Bursari', value: 'bursari' },
    { label: 'Fika', value: 'fika' },
    { label: 'Fune', value: 'fune' },
    { label: 'Geidam', value: 'geidam' },
    { label: 'Gujba', value: 'gujba' },
    { label: 'Gulani', value: 'gulani' },
    { label: 'Jakusko', value: 'jakusko' },
    { label: 'Karasuwa', value: 'karasuwa' },
  ],
  zamfara: [
    { label: 'Gusau', value: 'gusau' },
    { label: 'Kaura Namoda', value: 'kaura_namoda' },
    { label: 'Talata Mafara', value: 'talata_mafara' },
    { label: 'Anka', value: 'anka' },
    { label: 'Bakura', value: 'bakura' },
    { label: 'Birnin Magaji', value: 'birnin_magaji' },
    { label: 'Bungudu', value: 'bungudu' },
    { label: 'Chafe', value: 'chafe' },
    { label: 'Gummi', value: 'gummi' },
    { label: 'Zurmi', value: 'zurmi' },
  ],
};
